# Generated by Django 5.0.4 on 2024-07-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programs_img', models.CharField(max_length=100)),
                ('programs_name', models.CharField(max_length=100)),
                ('programs_detail', models.CharField(max_length=100)),
            ],
        ),
    ]
