# Generated by Django 5.0.4 on 2024-07-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='latprograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latprograms_img', models.CharField(max_length=100)),
                ('latprograms_name', models.CharField(max_length=100)),
                ('latprograms_detail', models.CharField(max_length=100)),
            ],
        ),
    ]
