# Generated by Django 5.0.4 on 2024-07-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_latprograms'),
    ]

    operations = [
        migrations.CreateModel(
            name='upcprograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcprograms_img', models.CharField(max_length=100)),
                ('upcprograms_name', models.CharField(max_length=100)),
                ('upcprograms_detail', models.CharField(max_length=100)),
            ],
        ),
    ]
