# Generated by Django 5.0.4 on 2024-07-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_img', models.CharField(max_length=100)),
                ('member_name', models.CharField(max_length=100)),
                ('member_work', models.CharField(max_length=100)),
                ('member_exp', models.CharField(max_length=100)),
            ],
        ),
    ]
