# Generated by Django 5.0.4 on 2024-07-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_img', models.FileField(default=None, max_length=250, null=True, upload_to='event/')),
            ],
        ),
    ]
