# Generated by Django 5.0.4 on 2024-07-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
