# Generated by Django 5.0.4 on 2024-07-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_event_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=models.CharField(max_length=50),
        ),
    ]
