# Generated by Django 5.0.4 on 2024-07-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='s_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(max_length=60)),
                ('s_img', models.CharField(max_length=60)),
                ('s_des', models.CharField(max_length=200)),
            ],
        ),
    ]
