# Generated by Django 5.0.4 on 2024-07-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicetitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='s_data',
        ),
    ]
