# Generated by Django 5.0.4 on 2024-07-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_servicetitle_delete_s_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_img', models.CharField(max_length=60)),
                ('s_des', models.CharField(max_length=200)),
            ],
        ),
    ]
