# Generated by Django 5.0.4 on 2024-07-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_servicedetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='servicetitle',
        ),
    ]
