# Generated by Django 5.0.4 on 2024-07-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_delete_servicetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicedetaill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_imgl', models.CharField(max_length=60)),
                ('s_desl', models.CharField(max_length=200)),
            ],
        ),
    ]
