# Generated by Django 5.0.4 on 2024-07-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0005_servicedetaill'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='s_title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
