# Generated by Django 5.0.4 on 2024-07-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0006_servicedetail_s_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetaill',
            name='s_titlel',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
