# Generated by Django 5.0.4 on 2024-07-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_img', models.CharField(max_length=60)),
                ('g_img1', models.CharField(max_length=60)),
                ('g_img2', models.CharField(max_length=60)),
            ],
        ),
    ]
