# Generated by Django 5.0.4 on 2024-07-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallimg',
            name='g_img1',
        ),
        migrations.RemoveField(
            model_name='gallimg',
            name='g_img2',
        ),
    ]
