# Generated by Django 5.0.4 on 2024-07-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0002_remove_gallimg_g_img1_remove_gallimg_g_img2'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallimg1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_img1', models.CharField(max_length=60)),
            ],
        ),
    ]
